spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/tpps
spring.datasource.username=tomas
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
app.jwt.issuer=tpps
app.jwt.accessTokenTtlMinutes=60
app.jwt.secret=${TPPS_JWT_SECRET:labaislaptasslaptazodisnestomastaipnoriirreikia}
server.port=8080